using System;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Robust.Roslyn.Shared;
using Robust.Roslyn.Shared.Helpers;
using static Robust.Shared.EntitySystemSubscriptionsGenerator.KnownTypes;

namespace Robust.Shared.EntitySystemSubscriptionsGenerator;

/// <summary>
/// This generator implements <c>EntitySystem.AutoSubscriptions()</c> for all <c>EntitySystem</c>s with methods
/// annotated by auto-subscription attributes. In case any attributes are applied to methods incorrectly, this generator
/// just silently ignores them and expects <see cref="EntitySystemSubscriptionGeneratorErrorAnalyzer"/> will complain
/// on its behalf (except in the case of attempting to add generated code to a non-partial type -- we complain about
/// that here).
/// </summary>
/// <seealso cref="EntitySystemSubscriptionGeneratorErrorAnalyzer"/>
[Generator(LanguageNames.CSharp)]
public class EntitySystemSubscriptionGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor NotPartial = new(
        Diagnostics.IdNonPartialContainingTypeForGeneratedSubscription,
        "Containing class must be declared as Partial",
        "Method is declared in type \"{0}\" which is not Partial",
        "Usage",
        DiagnosticSeverity.Error,
        true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var annotatedEntitySystems = Aggregate(
                GetEntityTypeCandidatesContainingAnnotatedMethods(context, AllSubscriptionMemberAttributeName),
                GetEntityTypeCandidatesContainingAnnotatedMethods(context, NetworkSubscriptionMemberAttributeName),
                GetEntityTypeCandidatesContainingAnnotatedMethods(context, LocalSubscriptionMemberAttributeName)
            ) // Get all candidate types containing subscription annotated methods
            .SelectMany((array, _) =>
                array.ToImmutableHashSet(PartialTypeInfo.WithoutLocationEqualityComparer)) // Dedupe
            .Combine(context.CompilationProvider)
            .Select((inputs, cancel) =>
                {
                    // For each EntitySystem we've identified as containing subscriptions...

                    var (partialTypeInfo, compilation) = inputs;
                    if (compilation.GetTypeByMetadataName(partialTypeInfo.GetMetadataName()) is not
                        { } entitySystemType)
                        return new EntitySystemInfo(partialTypeInfo, []);

                    // ... check all methods in the type to see if it's a subscription, assembling subscriptions into an array.
                    var subs = entitySystemType.GetMembers()
                        .OfType<IMethodSymbol>()
                        .Select(method =>
                        {
                            cancel.ThrowIfCancellationRequested();
                            return TryParseSubscriptions(method);
                        })
                        .OfType<SubscriptionInfo>()
                        .ToImmutableArray();

                    return new EntitySystemInfo(partialTypeInfo, subs);
                }
            );

        context.RegisterImplementationSourceOutput(
            // Only deal with types that have subscriptions.
            annotatedEntitySystems.Where(it => !it.Subscriptions.IsEmpty),
            (productionContext, info) =>
            {
                var (partialTypeInfo, subscriptions) = info;
                if (partialTypeInfo.CheckPartialDiagnostic(productionContext, NotPartial))
                    return;

                var subscriptionsSyntax = new StringBuilder();
                var generatedHandlerSyntax = new StringBuilder();
                for (var i = 0; i < subscriptions.Length; i++)
                {
                    productionContext.CancellationToken.ThrowIfCancellationRequested();
                    var method = subscriptions[i];
                    var subscriptionMethod = method.Type.ToSubscriptionMethod();
                    var typeArgs = string.Join(", ", method.TypeArgs);
                    if (method.Type == SubscriptionType.Local && method.HandlerKind != SubscriptionHandlerKind.None)
                    {
                        var generatedHandlerName = $"__GeneratedSubscription_{i}_{method.MethodName}";
                        subscriptionsSyntax.AppendLine($"        SubscribeGeneratedLocalEvent<{typeArgs}>({generatedHandlerName});");
                        AppendGeneratedHandler(generatedHandlerSyntax, generatedHandlerName, method);
                    }
                    else
                    {
                        subscriptionsSyntax.AppendLine($"        {subscriptionMethod}<{typeArgs}>({method.MethodName});");
                    }
                }

                var builder = new StringBuilder(@"
// <auto-generated />

using Robust.Shared.GameObjects;
using Robust.Shared.Analyzers;
using JetBrains.Annotations;
using System.Runtime.CompilerServices;

");
                partialTypeInfo.WriteHeader(builder);
                builder.AppendLine($@"
{{
    /// <inheritdoc />
    [MustCallBase]
    public override void AutoSubscriptions()
    {{
        base.AutoSubscriptions();

{subscriptionsSyntax}
    }}

{generatedHandlerSyntax}
}}
");
                partialTypeInfo.WriteFooter(builder);

                productionContext.AddSource(partialTypeInfo.GetGeneratedFileName(), builder.ToString());
            }
        );
    }

    private static void AppendGeneratedHandler(StringBuilder builder, string generatedHandlerName, SubscriptionInfo method)
    {
        var componentType = method.TypeArgs[0];
        var eventType = method.TypeArgs[1];

        builder.AppendLine($$"""
    private void {{generatedHandlerName}}(Robust.Shared.GameObjects.EntityUid uid, Robust.Shared.GameObjects.IComponent component, ref Robust.Shared.GameObjects.EntityEventBusUnit args)
    {
        ref var ev = ref Unsafe.As<Robust.Shared.GameObjects.EntityEventBusUnit, {{eventType}}>(ref args);
""");

        switch (method.HandlerKind)
        {
            case SubscriptionHandlerKind.ComponentValue:
                builder.AppendLine($"        {method.MethodName}(uid, ({componentType}) component, ev);");
                break;
            case SubscriptionHandlerKind.ComponentRef:
                builder.AppendLine($"        {method.MethodName}(uid, ({componentType}) component, ref ev);");
                break;
            case SubscriptionHandlerKind.EntityRef:
                builder.AppendLine($"        {method.MethodName}(new Robust.Shared.GameObjects.Entity<{componentType}>(uid, ({componentType}) component), ref ev);");
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(method.HandlerKind), method.HandlerKind, null);
        }

        builder.AppendLine("""
    }

""");
    }

    /// Returns <see cref="PartialTypeInfo"/>s for all types in the compilation that contain methods with the given
    /// <paramref name="attributeName">attribute</paramref>.
    private static IncrementalValuesProvider<PartialTypeInfo> GetEntityTypeCandidatesContainingAnnotatedMethods(
        IncrementalGeneratorInitializationContext context,
        string attributeName
    )
    {
        return context.SyntaxProvider.ForAttributeWithMetadataName(
                attributeName,
                (node, _) => node is MethodDeclarationSyntax,
                (ctx, _) =>
                {
                    if (ctx.TargetSymbol is not IMethodSymbol symbol ||
                        ctx.TargetNode is not MethodDeclarationSyntax { Parent: TypeDeclarationSyntax parentSyntax })
                        return null;

                    return PartialTypeInfo.FromSymbol(symbol.ContainingType, parentSyntax);
                })
            .Where(it => it is not null)
            .Select((it, _) => it ?? throw new("Unreachable"));
    }

    /// Tries to parse <paramref name="method"/>'s signature as an even subscription, returning the information required
    /// to make the subscription function call in the generated code. Returns <c>null</c> if the method is not a
    /// subscription, or is a subscription and its signature is invalid.
    private static SubscriptionInfo? TryParseSubscriptions(IMethodSymbol method)
    {
        return TryParseSubscription(
            method,
            AllSubscriptionMemberAttributeName,
            m => ToParsed(TryParseEntityEventHandler(m) ?? TryParseEntitySessionEventHandler(m))
        ) ?? TryParseSubscription(
            method,
            NetworkSubscriptionMemberAttributeName,
            m => ToParsed(TryParseEntityEventHandler(m) ?? TryParseEntitySessionEventHandler(m))
        ) ?? TryParseSubscription(
            method,
            LocalSubscriptionMemberAttributeName,
            TryParseLocalSubscription
        );
    }

    private static ParsedSubscription? TryParseLocalSubscription(IMethodSymbol method)
    {
        var broadcast = TryParseEntityEventHandler(method) ?? TryParseEntitySessionEventHandler(method);
        if (broadcast is { } broadcastArgs)
        {
            return new ParsedSubscription(broadcastArgs, SubscriptionHandlerKind.None);
        }

        if (TryParseComponentEventHandler(method) is { } component)
        {
            return new ParsedSubscription(
                component,
                method.Parameters[2].RefKind == RefKind.Ref
                    ? SubscriptionHandlerKind.ComponentRef
                    : SubscriptionHandlerKind.ComponentValue);
        }

        if (TryParseEntityEventRefHandler(method) is { } entity)
            return new ParsedSubscription(entity, SubscriptionHandlerKind.EntityRef);

        return null;
    }

    private static ParsedSubscription? ToParsed(ImmutableArray<string>? typeArgs)
    {
        if (typeArgs is not { } args)
            return null;

        return new ParsedSubscription(args, SubscriptionHandlerKind.None);
    }

    /// Tries to parse <paramref name="method"/>'s signature as <c>Robust.Shared.GameObjects.EntityEventHandler</c>.
    /// <returns>The type argument syntax to include in the subscription function call.</returns>
    public static ImmutableArray<string>? TryParseEntityEventHandler(IMethodSymbol method)
    {
        if (method.Parameters.Length != 1 ||
            method.Parameters[0].Type is not INamedTypeSymbol eventType)
            return null;

        return [eventType.ToString()];
    }

    /// Tries to parse <paramref name="method"/>'s signature as <c>Robust.Shared.GameObjects.EntitySessionEventHandler</c>.
    /// <returns>The type argument syntax to include in the subscription function call.</returns>
    public static ImmutableArray<string>? TryParseEntitySessionEventHandler(IMethodSymbol method)
    {
        if (method.Parameters.Length != 2 ||
            method.Parameters[0].Type is not INamedTypeSymbol eventType ||
            !TypeSymbolHelper.ShittyTypeMatch(
                method.Parameters[1].Type,
                EntitySessionEventArgsTypeName
            ))
            return null;

        return [eventType.ToString()];
    }

    /// Tries to parse <paramref name="method"/>'s signature as <c>Robust.Shared.GameObjects.EntityEventRefHandler</c>.
    /// <returns>The type argument syntax to include in the subscription function call.</returns>
    public static ImmutableArray<string>? TryParseEntityEventRefHandler(IMethodSymbol method)
    {
        if (method.Parameters.Length != 2 ||
            method.Parameters[0].Type is not INamedTypeSymbol entityType ||
            method.Parameters[1].Type is not INamedTypeSymbol eventType ||
            method.Parameters[1].RefKind != RefKind.Ref)
            return null;

        if (entityType.OriginalDefinition.ToDisplayString() != EntityTypeName ||
            entityType.TypeArguments is not [INamedTypeSymbol componentType] ||
            !TypeSymbolHelper.ImplementsInterface(componentType, IComponentTypeName))
            return null;

        return [componentType.ToString(), eventType.ToString()];
    }

    /// Tries to parse <paramref name="method"/>'s signature as <c>Robust.Shared.GameObjects.ComponentEventHandler</c>.
    /// <returns>The type argument syntax to include in the subscription function call.</returns>
    public static ImmutableArray<string>? TryParseComponentEventHandler(IMethodSymbol method)
    {
        if (method.Parameters.Length != 3 ||
            method.Parameters[0].Type is not INamedTypeSymbol entityUidType ||
            method.Parameters[1].Type is not INamedTypeSymbol componentType ||
            method.Parameters[2].Type is not INamedTypeSymbol eventType ||
            !TypeSymbolHelper.ShittyTypeMatch(entityUidType, EntityUidTypeName) ||
            !TypeSymbolHelper.ImplementsInterface(componentType, IComponentTypeName))
            return null;

        return [componentType.ToString(), eventType.ToString()];
    }

    private static SubscriptionInfo? TryParseSubscription(
        IMethodSymbol method,
        string annotationName,
        Func<IMethodSymbol, ParsedSubscription?> parseFunc
    )
    {
        if (annotationName.ToSubscriptionType() is not { } subType ||
            !AttributeHelper.HasAttribute(method, annotationName, out _) ||
            parseFunc(method) is not { } parsed)
            return null;

        return new SubscriptionInfo(method.Name, subType, parsed.TypeArgs, parsed.Kind);
    }

    /// Aggregates all of the <typeparamref name="T"/>s across all the given providers into a single array value
    /// provided by the returned provider.
    private static IncrementalValueProvider<ImmutableArray<T>> Aggregate<T>(
        IncrementalValuesProvider<T> first,
        params IncrementalValuesProvider<T>[] more
    )
    {
        return more.Aggregate(
            first.Collect(),
            (acc, valuesProvider) =>
                acc.Combine(valuesProvider.Collect())
                    .Select((values, _) => values.Left.AddRange(values.Right))
        );
    }

    private record struct EntitySystemInfo(PartialTypeInfo Type, EquatableArray<SubscriptionInfo> Subscriptions);

    private record struct ParsedSubscription(EquatableArray<string> TypeArgs, SubscriptionHandlerKind Kind);

    private record struct SubscriptionInfo(
        string MethodName,
        SubscriptionType Type,
        EquatableArray<string> TypeArgs,
        SubscriptionHandlerKind HandlerKind);

    private enum SubscriptionHandlerKind
    {
        None,
        ComponentValue,
        ComponentRef,
        EntityRef,
    }
}
